Get-AppxPackage *windowsalarms* | Remove-AppxPackage
Get-AppxPackage *Asphalt8Airborne* | Remove-AppxPackage
Get-AppxPackage *CandyCrushSaga* | Remove-AppxPackage
Get-AppxPackage *CandyCrushSodaSaga* | Remove-AppxPackage
Get-AppxPackage *CandyCrushFriendsSaga* | Remove-AppxPackage
Get-AppxPackage *DrawboardPDF* | Remove-AppxPackage
Get-AppxPackage *getstarted* | Remove-AppxPackage
Get-AppxPackage *Facebook* | Remove-AppxPackage
Get-AppxPackage *WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage *zunevideo* | remove-appxpackage
Get-AppxPackage *Finance* | Remove-AppxPackage
Get-AppxPackage *FitbitCoach* | Remove-AppxPackage
Get-AppxPackage *zunemusic* | remove-appxpackage
Get-AppxPackage *Maps* | Remove-AppxPackage
Get-AppxPackage *communicationsapps* | remove-appxpackage
Get-AppxPackage *WindowsCamera* | Remove-AppxPackage
Get-AppxPackage *People* | Remove-AppxPackage
Get-AppxPackage *News* | Remove-AppxPackage
Get-AppxPackage *messaging* | remove-appxpackage
Get-AppxPackage *Music* | Remove-AppxPackage
Get-AppxPackage *Minecraft* | Remove-AppxPackage
Get-AppxPackage *Netflix* | Remove-AppxPackage
Get-AppxPackage *officehub* | Remove-AppxPackage
Get-AppxPackage *OneNote* | Remove-AppxPackage
Get-AppxPackage *OneNote2016* | Remove-AppxPackage
Get-AppxPackage *Skype* | Remove-AppxPackage
Get-AppxPackage *solitairecollection* | Remove-AppxPackage
Get-AppxPackage *Sport* | Remove-AppxPackage
Get-AppxPackage *Store* | Remove-AppxPackage
Get-AppxPackage *sway* | remove-appxpackage
Get-AppxPackage *commsphone* | remove-appxpackage
Get-AppxPackage *windowsphone* | remove-appxpackage
Get-AppxPackage *Twitter* | Remove-AppxPackage
Get-AppxPackage *Video* | Remove-AppxPackage
Get-AppxPackage *xboxapp* | Remove-AppxPackage
Get-AppxPackage *xboxIdentityprovider* | Remove-AppxPackage
Get-AppxPackage *xing* | Remove-AppxPackage
Get-AppxPackage *LinkedIn* | Remove-AppxPackage
